version: '3.9'

services:
  app:
    build:
      context: .
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sh -c "cd next-app && npm run dev"
