import type { Metadata } from 'next';
import { Zen_Antique } from 'next/font/google';
import './globals.css';

const inter = Zen_Antique({
  weight: '400',
  display: 'swap',
  preload: false,
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Docker-Next.js-Example',
  description: 'Generated by Docker with create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
